INSERT INTO CATEGORY  VALUES (1, 'Breakfast');
INSERT INTO CATEGORY  VALUES (2, 'Lunch');
INSERT INTO CATEGORY  VALUES (3, 'Dinner');
INSERT INTO CATEGORY  VALUES (4, 'Desert');
INSERT INTO CATEGORY  VALUES (5, 'Drinks');
INSERT INTO CATEGORY  VALUES (6, 'Appetizers');
