CREATE TABLE [RECIPE] (
	ID int NOT NULL,
	RECIPE_NAME varchar(255) NOT NULL,
	AUTHOR varchar(255) NOT NULL,
	DATE_ADDED datetime NOT NULL,
	CATEGORY_ID int NOT NULL,
	PREP_TIME int NOT NULL,
	PREP_TIME_UNIT varchar(255) NOT NULL,
  CONSTRAINT [PK_RECIPE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [CATEGORY] (
	ID int NOT NULL,
	CATEGORY_NAME varchar(255) NOT NULL,
  CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [INGREDIENT] (
	ID int NOT NULL,
	INGREDIENT_NAME varchar(255) NOT NULL,
	MEASUREMENT varchar(255) NOT NULL,
	AMOUNT varchar(255) NOT NULL,
	INGREDIENT_LIST_ID int NOT NULL,
	RECIPE_ID int NOT NULL,
  CONSTRAINT [PK_INGREDIENT] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [USER] (
	ID int NOT NULL,
	FIRST_NAME varchar(255) NOT NULL,
	LAST_NAME varchar(255) NOT NULL,
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [DIRECTIONS] (
	ID int NOT NULL,
	DIRECTION text NOT NULL,
	STEP_NUMBER int NOT NULL,
	RECIPE_ID int NOT NULL,
  CONSTRAINT [PK_DIRECTIONS] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

