/****** Object:  Table [dbo].[CATEGORY]    Script Date: 6/18/2019 7:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORY](
	[ID] [int] NOT NULL,
	[CATEGORY] [varchar](max) NULL,
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIRECTION_LIST]    Script Date: 6/18/2019 7:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIRECTION_LIST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DIRECTION_ID] [int] NOT NULL,
 CONSTRAINT [PK_DIRECTION_LIST] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIRECTIONS]    Script Date: 6/18/2019 7:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIRECTIONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DIRECTIONS] [ntext] NULL,
	[STEP] [int] NULL,
 CONSTRAINT [PK_DIRECTIONS] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INGREDIENT]    Script Date: 6/18/2019 7:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INGREDIENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](max) NULL,
	[MEASUREMENT] [int] NULL,
	[UNIT] [varchar](max) NULL,
 CONSTRAINT [PK_INGREDIENT] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INGREDIENT_LIST]    Script Date: 6/18/2019 7:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INGREDIENT_LIST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INGREDIENT_ID] [int] NOT NULL,
 CONSTRAINT [PK_INGREDIENT_LIST] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECIPE]    Script Date: 6/18/2019 7:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECIPE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INGREDIENT_LIST_ID] [int] NULL,
	[DATE_ADDED] [datetime] NULL,
	[FIRST_NAME] [varchar](max) NULL,
	[LAST_NAME] [varchar](max) NULL,
	[DIRECTION_LIST_ID] [int] NULL,
	[TIME_MINUTES] [int] NULL,
	[CATEGORY_ID] [int] NULL,
 CONSTRAINT [PK_RECIPE] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIRECTION_LIST]  WITH CHECK ADD  CONSTRAINT [FK_DIRECTION_LIST_DIRECTION] FOREIGN KEY([DIRECTION_ID])
REFERENCES [dbo].[DIRECTIONS] ([ID])
GO
ALTER TABLE [dbo].[DIRECTION_LIST] CHECK CONSTRAINT [FK_DIRECTION_LIST_DIRECTION]
GO
ALTER TABLE [dbo].[INGREDIENT_LIST]  WITH CHECK ADD  CONSTRAINT [FK_INGREDIENT_LIST_INGREDIENT] FOREIGN KEY([INGREDIENT_ID])
REFERENCES [dbo].[INGREDIENT] ([ID])
GO
ALTER TABLE [dbo].[INGREDIENT_LIST] CHECK CONSTRAINT [FK_INGREDIENT_LIST_INGREDIENT]
GO
ALTER TABLE [dbo].[RECIPE]  WITH CHECK ADD  CONSTRAINT [FK_RECIPE_CATEGORY] FOREIGN KEY([CATEGORY_ID])
REFERENCES [dbo].[CATEGORY] ([ID])
GO
ALTER TABLE [dbo].[RECIPE] CHECK CONSTRAINT [FK_RECIPE_CATEGORY]
GO
ALTER TABLE [dbo].[RECIPE]  WITH CHECK ADD  CONSTRAINT [FK_RECIPE_DIRECTION_LIST] FOREIGN KEY([DIRECTION_LIST_ID])
REFERENCES [dbo].[DIRECTION_LIST] ([ID])
GO
ALTER TABLE [dbo].[RECIPE] CHECK CONSTRAINT [FK_RECIPE_DIRECTION_LIST]
GO
ALTER TABLE [dbo].[RECIPE]  WITH CHECK ADD  CONSTRAINT [FK_RECIPE_INGREDIENT_LIST] FOREIGN KEY([INGREDIENT_LIST_ID])
REFERENCES [dbo].[INGREDIENT_LIST] ([ID])
GO
ALTER TABLE [dbo].[RECIPE] CHECK CONSTRAINT [FK_RECIPE_INGREDIENT_LIST]
GO
